# permissions for end users to edit fluxapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: fluxer
    app.kubernetes.io/managed-by: kustomize
  name: fluxapp-editor-role
rules:
- apiGroups:
  - apps.kloudy.uk
  resources:
  - fluxapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.kloudy.uk
  resources:
  - fluxapps/status
  verbs:
  - get
