---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps.kloudy.uk
  resources:
  - fluxapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.kloudy.uk
  resources:
  - fluxapps/finalizers
  verbs:
  - update
- apiGroups:
  - apps.kloudy.uk
  resources:
  - fluxapps/status
  verbs:
  - get
  - patch
  - update
